name: Verify DevKit

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "POETRY_HOME=$HOME/.local" >> $GITHUB_ENV
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry (disable package mode)
        run: |
          poetry config virtualenvs.in-project true
          poetry config package-mode false

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run --all-files
